In [30]:
'''Consider the below code to answer further questions:-'''

import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)

In [31]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [32]:
list_

['1', '2', '3', '4', '5']

In [21]:
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both
   the variables.

In [33]:
'''Yes, there is a difference in the data type of variables list_ and array_list. list_ is a Python list object while array_list 
   is a NumPy array object.'''
# printing data types of both variables
print(type(list_)) 
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [34]:
for i in list_ :
    print(type(i))
print("+.................+")
for i in array_list :
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
+.................+
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and 
arra_list? If so then print the data types of each and every element present in both the variables, list_ 
and arra_list.

In [35]:
array_list = np.array(object = list_, dtype = int)
print(array_list)
print("....data type of each elemrnt in list_ given below .......")
for i in list_ :
    print(type(i))
print("....data type of each elemrnt in array_list given below .......")
for i in array_list :
    print(type(i))

[1 2 3 4 5]
....data type of each elemrnt in list_ given below .......
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
....data type of each elemrnt in array_list given below .......
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [36]:
'''Consider the below code to answer further questions:'''

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

In [39]:
print(np.shape(num_list))
print(np.size(num_list))

(2, 3)
6


In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3)

In [43]:
matrix=np.zeros((3,3))
matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
print(np.shape(matrix))
print(np.size(matrix))

(3, 3)
9


In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.

In [49]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])